spring.application.name=Device_Tracking
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
ring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false


spring.thymeleaf.cache=false
server.address=0.0.0.0
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true